/*
 Generated by typeshare 1.13.2
*/


export interface AccountEntry {
	id: string;
	account: string;
	password_hash: string;
	create_time: string;
	update_time: string;
}

export interface LoginRequest {
	account: string;
	password: string;
}

export interface UserEntry {
	id: string;
	account: string;
	nickname: string;
	avatar_url: string;
	create_time: string;
	update_time: string;
}

