/*
 Generated by typeshare 1.13.2
*/


export interface AddNoteRequest {
	title: string;
	content: string;
}

export interface ESAnalyzeNoteHighlight {
	title?: string[];
	content?: string[];
}

export interface ESNoteEntry {
	account: string;
	title: string;
	content: string;
	create_time: number;
	update_time: number;
}

export interface NotePageRequest {
	page?: number;
	page_size?: number;
	analyze?: string;
}

