[package]
name = "server-common"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
chrono = { version = "0.4" }
dotenvy = { "version" = "0.15" }
opentelemetry = { version = "0.29" }
opentelemetry_sdk = { version = "0.29" }
opentelemetry-stdout = { version = "0.29" }
opentelemetry-otlp = { version = "0.29" }
opentelemetry-http = { version = "0.29" }
opentelemetry-appender-tracing = { version = "0.29" }
tracing-opentelemetry = "0.30.0"
opentelemetry-jaeger-propagator = "0.29.0"
tracing = "0.1"
serde_json = "1.0"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "registry",
    "std",
    "fmt",
] }
reqwest = { version = "0.12" ,features = ["stream","json"]}
serde = { version = "1" , features = ["derive"]}
jsonwebtoken = "9.3"
base64 = "0.22"
regex="1.11"
typeshare = "1"